color: null
description: null
fieldLayouts:
  31dccd43-cabc-4be5-b16d-50d43d28c1b8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-08T17:51:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8a941a55-a28a-4892-9975-9658fe5b2318
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T17:58:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67fcc8e0-ba5a-4580-9981-d2396d4e9e32 # Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1691c842-0bd8-4384-a9f0-afc2f82e79ec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T17:58:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 556ba6b4-1f6e-4e24-9886-8d1f43ddb8bc # Drink Visibility
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8eb11b8-d7da-4451-9cbf-82b0dbf7fd03
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T17:58:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1cc42db4-c0f6-423d-9347-8e776bb43a58 # Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab9b42ef-7be0-4623-a42f-42d91155a677
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T17:58:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a22c0783-c99f-406f-a934-529b0b809fac # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bacf799-771e-4273-b5e6-1a423bd2c9cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c353205-1e1e-4de7-a833-1a0f17c65d5b
        userCondition: null
handle: drinks
hasTitleField: true
icon: null
name: Drinks
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
