color: null
description: null
fieldLayouts:
  72355887-8bab-492f-88c6-d95354297d5a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-11T14:21:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69efb4b4-b5d5-4747-b218-b8ccfd4b15fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-11T14:25:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 35c9edd8-be10-4e6b-8390-5daa27a96a9b # Tab Owner
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1cf1159-d108-43e5-84b1-5422344e6587
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-11T14:25:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6a8e6fec-287a-47e7-9ab1-4ca8aff38e4c # Tab Status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ede4c036-8478-4f67-8581-7052d6bd138f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-11T14:25:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 27d37b36-6703-4372-8d44-1bbc2d4a599b # Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d37e837-68be-4f23-b267-dfd1075787d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T19:42:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 195c2b3f-fd22-4f62-aa83-264d2e89a049 # Qty
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c8e5ee1-6627-448f-a8da-5c3b7795ce4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a0b4286a-d724-47f7-a9dd-bc9945f3e7b0
        userCondition: null
handle: tabs
hasTitleField: true
icon: null
name: Tabs
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
