columnSuffix: null
handle: selectionSent
instructions: null
name: 'Selection Sent'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
