columnSuffix: null
handle: statusAdmin
instructions: null
name: 'Status Admin'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Geselecteerd
        -
          - value
          - geselecteerd
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Niet Geselecteerd'
        -
          - value
          - nietGeselecteerd
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Nog Te Bepalen'
        -
          - value
          - nogTeBepalen
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
