defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4ebcefd2-cd60-4639-97dc-a64377d08c24 # Availability
handle: availability
maxAuthors: 1
name: Availability
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0a105f38-fbd5-4242-aba4-6c12d557259c: # Table Tennis Tool
    enabledByDefault: true
    hasUrls: true
    template: availability/_entry.twig
    uriFormat: 'availability/{slug}'
type: channel
