defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 13564983-865b-457e-a301-f41345dec271 # Drinks
handle: drinks
maxAuthors: 1
name: Drinks
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0a105f38-fbd5-4242-aba4-6c12d557259c: # Table Tennis Tool
    enabledByDefault: true
    hasUrls: true
    template: drinks/_entry.twig
    uriFormat: 'drinks/{slug}'
type: channel
