dateModified: 1754321974
email:
  fromEmail: charlotte.billiet25@gmail.com
  fromName: 'Table Tennis Tool'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a105f38-fbd5-4242-aba4-6c12d557259c: 'Table Tennis Tool' # Table Tennis Tool
    4bca08c3-02a0-4f8e-9125-6b09828edd49: 'Ploeg C' # Ploeg C
    4e17cb9a-52a4-49a2-a715-1d4f8e4097dd: 'Table Tennis Tool' # Table Tennis Tool
    7fa6534c-773d-4769-9d22-a2f534c3b5f4: Location # Location
    011dad69-aa0c-45c9-81b7-0144dc8f07f4: TeamA # TeamA
    39dab611-7a06-4450-972e-0d8f90d62b79: 'Public Schema' # Public Schema
    64e5c2be-5d40-44e0-a6f3-08015b562725: 'Ploeg A' # Ploeg A
    4663245d-cb44-4730-80b3-a5caba313759: 'CSV Entries' # CSV Entries
    da57e7e9-7915-4119-aa7e-730ad58dd0ac: Date/Time # Date/Time
    dd79136e-3da1-41f1-b9cb-e9c36475201d: 'Ploeg B' # Ploeg B
    fcbc034f-08a7-4728-bcb0-b0178b95230c: Teams # Teams
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
system:
  edition: pro
  live: true
  name: 'Table Tennis Tool'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
